name-template: 'v$NEXT_PATCH_VERSION 🌟'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 🚀 Features
    commit:
      - "^feat"
  - title: 🐛 Bug Fixes
    commit:
      - "^fix"
  - title: 📚 Documentation
    commit:
      - "^docs"
change-template: '- $TITLE @$AUTHOR'