name: Auto Release Drafter
on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    premissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}